source "https://rubygems.org"

ruby '~> 2.3.0'

gem 'adsf'
gem 'builder'
gem 'kramdown'
gem 'sass'
gem 'mime-types'
gem 'compass'
gem 'nokogiri'
gem 'coderay'
gem 'haml'
gem 'json'
gem 'rainpress'
gem 'jsmin'
gem 'htmlcompressor'
gem 'nanoc', '4.4.1'
gem 'nanoc-external'
gem 'guard-nanoc'
#gem 'typogruby',	'~> 1.0.18'